spring:
  datasource:
    dynamic:
      enabled: false #启用动态数据源，默认true 自行实现了注解和手工设置 CodeEntityAdvancedController
      primary: master
      datasource:
        master:
          driver-class-name: oracle.jdbc.OracleDriver
          jdbc-url: jdbc:oracle:thin:@192.168.3.161:1521:jc
          username: jc
          password: 123456
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://192.168.3.163:3306/ai-dream
          username: root
          password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.whalefall541.mybatisplus.samples.generator.system.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
