spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@192.168.3.161:1521:jc
          username: jc
          password: 123456
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.3.163:3306/ai-dream
          username: root
          password: root
  # Quartz配置 - 使用自定义配置类
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always # 自动创建表结构

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.whalefall541.mybatisplus.samples.generator.system.po
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
